global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'health_probe'

    static_configs:
      - targets: ['health_probe:8080']
        labels:
          instance: 'dev'

rule_files:
  - '/etc/prometheus/rules/*.yml'

