name: Compute Horde SDK CD (docs)

on:
  push:
    branches:
      - master
    tags:
      - 'sdk-v*'  # push events to matching sdk-v*, i.e. sdk-v1.0, sdk-v20.15.10
      - 'draft/sdk-v*'
    paths:
      - 'compute_horde_sdk/**'

env:
  PYTHON_DEFAULT_VERSION: "3.12"

jobs:
  # Job for Github Pages publishing
  publish-docs:
    defaults:
      run:
        working-directory: ./compute_horde_sdk
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required by sphinx-multiversion

      - name: Set up Python ${{ env.PYTHON_DEFAULT_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_DEFAULT_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.x"
          enable-cache: true

      - name: Install dependencies
        run: python -m pip install --upgrade nox

      - name: Build the docs 📑
        run: nox -vs docs

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload docs 📑 to Github Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./compute_horde_sdk/docs/build/html"

      - name: Publish docs 📑 to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
