name: Compute Horde SDK CD

# This workflow requires https://docs.pypi.org/trusted-publishers/ to be enabled for the repository.
# Follow instructions from this link to enable it.
# Use this workflow (`publish.yml`) in the configuration.
# Please note this process has to be repeated for Test PyPI and PyPI separately.

on:
  push:
    tags:
      - 'sdk-v*'  # push events to matching sdk-v*, i.e. sdk-v1.0, sdk-v20.15.10
      - 'draft/sdk-v*'

env:
  PYTHON_DEFAULT_VERSION: "3.12"

jobs:
  # Job to get version from tag
  get-version:
    runs-on: ubuntu-latest
    outputs:
      draft: ${{ steps.get-version.outputs.draft }}
    defaults:
      run:
        working-directory: ./compute_horde_sdk
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get version from tag
        id: get-version
        run: |
          if [[ ${{ github.ref }} == refs/tags/sdk-v* ]]; then
              echo "draft=false" >> "$GITHUB_OUTPUT"
          else
              echo "draft=true" >> "$GITHUB_OUTPUT"
          fi

  # Job for Python package publishing
  publish-python:
    needs: get-version
    defaults:
      run:
        working-directory: ./compute_horde_sdk
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      id-token: write  # allows publishing to PyPI
      contents: write  # allows uploading a GitHub release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.PYTHON_DEFAULT_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_DEFAULT_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.x"
          enable-cache: true

      - name: Build
        run: uv build

      - name: Publish distribution 📦 to TestPyPI
        if: ${{ needs.get-version.outputs.draft == 'true' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: compute_horde_sdk/dist/

      - name: Publish distribution 📦 to PyPI
        if: ${{ needs.get-version.outputs.draft == 'false' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: compute_horde_sdk/dist/


