name: "CD: facilitator (testing)"

on:
  push:
    branches:
      - 'deploy-facilitator-testing'

jobs:
  deploy:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./facilitator
    steps:
      - id: app_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}
          owner: ${{ github.repository_owner }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: poor man's deploy
        run: |
          DEPLOY_KEY_FILE=$(mktemp)
          echo "${{ secrets.FACILITATOR_TESTING_DEPLOY_SSH_KEY }}" > "$DEPLOY_KEY_FILE"
          chmod 600 "$DEPLOY_KEY_FILE"

          git remote add deploy ${{ secrets.FACILITATOR_TESTING_DEPLOY_POORMANS_URL }}
          GIT_SSH_COMMAND="ssh -i $DEPLOY_KEY_FILE -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
            git push deploy HEAD:master -f
          
          export TAG=deployed-facilitator-testing-`date -u +"%Y-%m-%dT%H.%M.%S"`
          git tag $TAG
          git push origin $TAG
