name: Run library QA

on:
  push:
    branches: [master, main]
  pull_request:

env:
  PYTHON_DEFAULT_VERSION: "3.11"

jobs:
  linter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./compute_horde
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_DEFAULT_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_DEFAULT_VERSION }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.x"
          enable-cache: true
      - name: Install dependencies
        run: uv tool install nox
      - name: Run linters
        run: nox -vs lint
      - name: Check for missing migrations
        run: nox -vs check_missing_migrations
  type_check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./compute_horde
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_DEFAULT_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_DEFAULT_VERSION }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.x"
          enable-cache: true
      - name: Install dependencies
        run: uv tool install nox
      - name: Run mypy
        run: nox -vs type_check
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./compute_horde
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_DEFAULT_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_DEFAULT_VERSION }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.x"
          enable-cache: true
      - name: Install dependencies
        run: uv tool install nox
      - name: Run unit tests
        run: nox -vs test
